"""Convert log contents from string to array

Revision ID: 312ddd5eef18
Revises: 5abfaa67fac2
Create Date: 2024-06-25 15:27:16.977003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312ddd5eef18'
down_revision = '5abfaa67fac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization_logs', schema=None) as batch_op:
        batch_op.alter_column('contents',
               existing_type=sa.VARCHAR(),
               type_=sa.ARRAY(sa.VARCHAR()),
               nullable=True,
               postgresql_using='contents::VARCHAR[]'
               )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization_logs', schema=None) as batch_op:
        batch_op.alter_column('contents',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
