"""Add relationships

Revision ID: 9d526322447a
Revises: 6ade2ffd381c
Create Date: 2024-06-06 03:39:51.340198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d526322447a'
down_revision = '6ade2ffd381c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_assignments_organization_id_organizations'), 'organizations', ['organization_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_assignments_item_id_items'), 'items', ['item_id'], ['id'])

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_items_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_memberships_organization_id_organizations'), 'organizations', ['organization_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_memberships_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('organization_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_organization_logs_organization_id_organizations'), 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_requests_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_requests_organization_id_organizations'), 'organizations', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_requests_organization_id_organizations'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_requests_user_id_users'), type_='foreignkey')
        batch_op.drop_column('organization_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('organization_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_organization_logs_organization_id_organizations'), type_='foreignkey')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_memberships_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_memberships_organization_id_organizations'), type_='foreignkey')
        batch_op.drop_column('organization_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_items_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_assignments_item_id_items'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_assignments_organization_id_organizations'), type_='foreignkey')
        batch_op.drop_column('organization_id')
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###
